# ENVIRONMENT VARIABLES
source "$HOME/.exports"

# SOURCE ALIASES
source "$HOME/.aliases"

# SOURCE CUSTOM FUNCTIONS
source "$HOME/.functions"

# Fix keyboard, just in case
fixkeyboard

# Load the wal theme.
(cat ~/.cache/wal/sequences &)
source ~/.cache/wal/colors-tty.sh
