#!/bin/bash

# Terminal colors.

colors() {
	if [[ -n "$ZSH_VERSION" ]]; then
		for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done
	fi

    red='\e[1;31m%s\e[0m\n'
    green='\e[1;32m%s\e[0m\n'
    yellow='\e[1;33m%s\e[0m\n'
    blue='\e[1;34m%s\e[0m\n'
    magenta='\e[1;35m%s\e[0m\n'
    cyan='\e[1;36m%s\e[0m\n'
    printf "$green"   "green"
    printf "$red"     "red"
    printf "$yellow"  "yellow"
    printf "$blue"    "blue"
    printf "$magenta" "magenta"
    printf "$cyan"    "cyan"
}

# Smart tmux functions.

tmux-attach-fn() {
	if [ -z "$1" ]; then
		tmux attach	
	else
		tmux attach -t "$@"
	fi
}

tmux-kill-session-fn() {
	if [ -z "$1" ]; then
		tmux kill-session	
	else
		tmux kill-session -t "$@"
	fi
}

tmux-new-fn() {
	if [ -z "$1" ]; then
		tmux new
	else
		tmux new -t "$@"
	fi
}
