#!/bin/sh

# Import wal colors.

. $HOME/.cache/wal/colors.sh

screen=$(cat ~/.cache/wal/wal)

B='00000000'  # blank
C='ffffff22'  # clear ish
D="${foreground}cc"  # default
T="${foreground}ee"  # text
W="${color1}bb"  # wrong
V="${color2}bb"  # verifying

~/.programs-from-git/i3lock-color/x86_64-pc-linux-gnu/i3lock \
--image "$screen"     \
--tiling              \
--insidevercolor=$B   \
--ringvercolor=$V     \
\
--insidewrongcolor=$B \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$B       \
--wrongcolor=$B       \
--timecolor=$D        \
--datecolor=$D        \
--layoutcolor=$D      \
--keyhlcolor=$W       \
--bshlcolor=$W        \
\
--screen 1            \
--indicator
