#!/bin/bash

# Script that reads the output from i3status
# and appends an element for Spotify playback
# status, using playerctl.
# Contains a free code-injection vunerability!

while read line; do
    # Fetch the data with playerctl.
    status=$(printf "%q" | playerctl status --player=spotify)
    artist=$(printf "%q" | playerctl metadata artist --player=spotify)
    title=$(printf "%q" | playerctl metadata title --player=spotify)
    album=$(printf "%q" | playerctl metadata album --player=spotify)

    # If the status is "Paused", change the bar.
    if [ "$status" = "Paused" ]; then
        paused="(paused) "
    else
        paused=""
    fi

    # Generate the new bar (JSON object).
    newbar="{\"color\": \"do not change\",\
    \"full_text\": \"${paused}  ${artist} - ${title} (${album})\",\
    \"name\": \"spotify\"}"

    # Modify the input, appending the new bar element.
    if [ "$status" = "Not available" ]; then
        echo "$line"
    else
        echo "$line" | sed "s|\[{|\[$newbar,{|g"
    fi
done
