#!/bin/sh

# Configure X
xrdb -merge ~/.Xdefaults &

# Start screensaver
# xscreensaver -no-splash &

# set wallpaper
# feh --bg-scale /home/pseifer/CONFIG/wallpaper.jpg &

# Start sound server
# pulseaudio --start &

# Set keyboard speed
xset r rate 160 30

/usr/bin/setxkbmap -option "ctrl:nocaps"

# manage power
xfce4-power-manager &

# exec ck-launch-session dbus-launch --sh-syntax --exit-with-session xmonad
