# ZSH configuration setup.

# .zshenv   | used (this file), only sources .profile
# .zprofile | not currently used (maybe add slow stuff)
# .zshrc		| used, interactive setup
# .zlogin   | not used
# .zlogout  | not used

source "$HOME/.profile"

skip_global_compinit=1
