# OH-MY-ZSH CONFIGURATION

# Path to your oh-my-zsh installation.
export ZSH=/home/pseifer/.oh-my-zsh

ZSH_THEME="mortalscumbag"

CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"

# DISABLE_AUTO_UPDATE="true"
# export UPDATE_ZSH_DAYS=13

# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"

# ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

# DISABLE_UNTRACKED_FILES_DIRTY="true"

# HIST_STAMPS="mm/dd/yyyy"

# ZSH_CUSTOM=/path/to/new-custom-folder

# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git debian lol python command-not-found sudo urltools)



# USER CONFIGURATION

# keybinds
#bindkey -v
bindkey -M vicmd '?' history-incremental-search-backward
bindkey -M viins 'jj' vi-cmd-mode
bindkey '^R' history-incremental-search-backward

# VI mode stuff
# bindkey -v
#function zle-line-init zle-keymap-select {
#     VIM_PROMPT="%{$fg_bold[yellow]%} [% NORMAL]%  %{$reset_color%}"
#     RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/}$(git_custom_status) $EPS1"
#     zle reset-prompt
# }
#
# zle -N zle-line-init
# zle -N zle-keymap-select
export KEYTIMEOUT=1

export PATH="/home/pseifer/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/pseifer/.cargo/bin"

export RUST_SRC_PATH="/home/pseifer/.src/rust/src"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=en_GB.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='edit' # 'edit' alias

export PROMPT_EOL_MARK=''
# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/dsa_id"
export PATH=$PATH:/home/pseifer/.config/panel:/home/pseifer/.local/bin

# term
export TERM=xterm-256color

# Base16 Shell
#BASE16_SHELL="$HOME/.config/base16-shell/scripts/base16-eighties.sh"
#[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# SOURCE ALIASES
source "$HOME/.aliases"

# SOURCE CUSTOM FUNCTIONS
source "$HOME/.functions"

# PYENV
#export PYENV_ROOT="$HOME/.pyenv"
#export PATH="$PYENV_ROOT/bin:$PATH"
#eval "$(pyenv init -)"

# Fix keyboard, just in case
fixkeyboard

# Reload X resources, just because
reloadxres

# FISH-STYLE EXTENSION
# from: https://github.com/zsh-users/zsh-syntax-highlighting
# https://github.com/zsh-users/zsh-syntax-highlighting
# configuration
ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=white,bold,bg=red')
source /home/pseifer/.programs-from-git/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# OPAM configuration
. /home/pseifer/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
