# OH-MY-ZSH CONFIGURATION

# Path to your oh-my-zsh installation.
export ZSH=/home/pseifer/.oh-my-zsh

ZSH_THEME="mortalscumbag"

CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"

# DISABLE_AUTO_UPDATE="true"
# export UPDATE_ZSH_DAYS=13

# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"

# ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

# DISABLE_UNTRACKED_FILES_DIRTY="true"

# HIST_STAMPS="mm/dd/yyyy"

# ZSH_CUSTOM=/path/to/new-custom-folder

# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(vi-mode git debian lol python command-not-found sudo urltools vim-interaction)

# ZSH INIT
source "$ZSH/oh-my-zsh.sh"



# USER CONFIGURATION

# VI
bindkey -v

# Keybinds
bindkey -M vicmd '?' history-incremental-search-backward
bindkey 'jj' vi-cmd-mode
bindkey '^R' history-incremental-search-backward

# ENVIRONMENT VARIABLES
source "$HOME/.exports"

# SOURCE ALIASES
source "$HOME/.aliases"

# SOURCE CUSTOM FUNCTIONS
source "$HOME/.functions"

# Fix keyboard, just in case
fixkeyboard

# Load the wal theme.
(cat ~/.cache/wal/sequences &)
source ~/.cache/wal/colors-tty.sh

# Init FISH-style highlighting extension
ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=white,bold,bg=red')
source /home/pseifer/.programs-from-git/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
