#!/bin/bash

if punkt test --pack "apt"; then
    wget https://repo2.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.3-3_all.deb
    sudo dpkg -i ./protonvpn-stable-release_1.0.3-3_all.deb && sudo apt update
    sudo apt install proton-vpn-gnome-desktop
fi
