#!/bin/bash

# Ensure .local/share exists (for /fonts).
mkdir -p ~/.local/share/

if punkt test --os linux; then
    cd "$HOME/.local/share/" || exit
    curl -0L "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/SourceCodePro.zip > SauceCodePro.zip"
    unzip "SauceCodePro.zip" -d "fonts"
    rm "SauceCodePro.zip"

    # Refresh font cache.
    fc-cache -f -v
else
    brew tap homebrew/cask-fonts
    brew install font-sauce-code-pro-nerd-font
fi
