#!/bin/bash

# Ensure .local/share exists (for /fonts).
mkdir -p ~/.local/share

if punkt test --os linux; then
    punkt curl --zip "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/SourceCodePro.zip" --name "sauce-code-pro"
    punkt link --absolute-name "sauce-code-pro" "${HOME}/.local/share/fonts"

    # Refresh font cache.
    fc-cache -f -v
else
    brew tap homebrew/cask-fonts
    brew install font-sauce-code-pro-nerd-font
fi
