#!/bin/bash

# Setup a generic development session in a certain folder.
# tmux-dev <path> <name>
tmux-dev() {
    folder="${1:-$PWD}"
    dev="${2:-dev}"
    # Create a dev window and start VI.
    tmux new-window -n "${dev}" -c "$folder"
    tmux send-keys -t "${dev}" "cd $folder; vi ." 'Enter'
    # Split one third off.
    tmux split-window -h -p 30 -t "${dev}"
    tmux send-keys -t "${dev}" "cd $folder; clear" 'Enter'
    # Create a swap window; cicle windows with C-a C-n / C-a C-p
    tmux new-window -n "${dev}-swap"
    tmux send-keys -t "${dev}-swap" "cd $folder; clear" 'Enter'
    tmux last-window
}

# Setup a python development session in a certain folder.
# tmux-dev <path> <name>
tmux-py() {
    folder="${1:-$PWD}"
    dev="${2:-pydev}"
    # Create a dev window and start VI.
    tmux new-window -n "${dev}" -c "$folder"
    tmux send-keys -t "${dev}" "cd $folder; pyva; vi ." 'Enter'
    # Split one third off.
    tmux split-window -h -p 30 -t "${dev}"
    tmux send-keys -t "${dev}" "cd $folder; pyva; clear" 'Enter'
    # Split vertically.
    tmux split-window -t "${dev}"
    tmux send-keys -t "${dev}" "cd $folder; pyva; python3" 'Enter'
}

# Print terminal colors.
colors() {
    if [[ -n "$ZSH_VERSION" ]]; then
        for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done
    fi
    # echo -e "\e[30mcolor\e[0m black"
    # echo -e "\e[31mcolor\e[0m red"
    # echo -e "\e[32mcolor\e[0m green"
    # echo -e "\e[33mcolor\e[0m yellow"
    # echo -e "\e[34mcolor\e[0m blue"
    # echo -e "\e[35mcolor\e[0m magenta"
    # echo -e "\e[36mcolor\e[0m cyan"
    # echo -e "\e[37mcolor\e[0m white"

    # echo -e "\e[1;30mcolor\e[0m black"
    # echo -e "\e[1;31mcolor\e[0m red"
    # echo -e "\e[1;32mcolor\e[0m green"
    # echo -e "\e[1;33mcolor\e[0m yellow"
    # echo -e "\e[1;34mcolor\e[0m blue"
    # echo -e "\e[1;35mcolor\e[0m magenta"
    # echo -e "\e[1;36mcolor\e[0m cyan"
    # echo -e "\e[1;37mcolor\e[0m white"
}
