#!/bin/bash

# File system.

alias l="ls --color --group-directories-first -AlFh"
alias ll="ls --color --group-directories-first -AlFhL"
alias tr='tree -C .'
alias tra='tree -Ca .'
alias tr1='tree -C . -L 1'
alias tr2='tree -C . -L 2'
alias tr3='tree -C . -L 3'
alias tr4='tree -C . -L 4'
alias tr5='tree -C . -L 5'
alias trl='tree . -C -L'
alias tral='tree . -Ca -L'

# Navigation.

alias ..=../
alias ...=../../
alias ....=../../../

# Safety.

alias rm='rm -I --preserve-root'
alias rmr='rm -rI --preserve-root'
alias ln='ln -i'
alias mv='mv -i'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# Editor (666).

alias vim='nvim'
alias vi='nvim'
alias emacs='nvim'
alias nano='nvim'

# Git.

alias agent-unlock='eval `ssh-agent -s`; ssh-add'

alias ggl='git log'
alias ggb='git branch'
alias ggs='git status'
alias ggp='git push'
alias ggc='git commit'
alias ggcm='git commit -m'
alias gga='git add'

# Utility.

alias url-decode='python3 -c "import sys, urllib.parse as ulp; print(ulp.unquote(sys.argv[1]))"'
alias url-encode='python3 -c "import sys, urllib.parse as ulp; print(ulp.quote(sys.argv[1]))"'

alias fix-keyboard-ctrl='setxkbmap -option "ctrl:nocaps"'
alias fix-keyboard-rate='xset r rate 250 30'
alias fixkb='fix-keyboard-ctrl; fix-keyboard-rate'
alias FIXKB='xdotool key Caps_Lock; fixkb'

alias c='clear'

# TMUX

alias tdev='tmux-dev'
alias tpy='tmux-py'

# Zsh

alias zsh-reload='. $HOME/.zshrc'

# Python

alias pyvn='python3 -m venv venv'
alias pyva='source venv/bin/activate'
alias pyvd='deactivate'

# WSL
alias wslgui='export DISPLAY=localhost:0.0'
