#!/bin/bash

# Terminal colors.

colors() {
    if [[ -n "$ZSH_VERSION" ]]; then
        for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done
    fi
    # echo -e "\e[30mcolor\e[0m black"
    # echo -e "\e[31mcolor\e[0m red"
    # echo -e "\e[32mcolor\e[0m green"
    # echo -e "\e[33mcolor\e[0m yellow"
    # echo -e "\e[34mcolor\e[0m blue"
    # echo -e "\e[35mcolor\e[0m magenta"
    # echo -e "\e[36mcolor\e[0m cyan"
    # echo -e "\e[37mcolor\e[0m white"

    # echo -e "\e[1;30mcolor\e[0m black"
    # echo -e "\e[1;31mcolor\e[0m red"
    # echo -e "\e[1;32mcolor\e[0m green"
    # echo -e "\e[1;33mcolor\e[0m yellow"
    # echo -e "\e[1;34mcolor\e[0m blue"
    # echo -e "\e[1;35mcolor\e[0m magenta"
    # echo -e "\e[1;36mcolor\e[0m cyan"
    # echo -e "\e[1;37mcolor\e[0m white"
}
