#!/bin/bash

# More stuff to add here:
# brew install syncthing
# brew services start syncthing

# linux: install syncthing and launch service
# punkt_pack_install syncthing
# systemctl --user enable syncthing.service
# systemctl --user start syncthing.service

# Use something like `punkt service "syncthing"` which
# launches with systemctl or brew, depending on the system.
# (Perhaps include also supervisorctl reload supervisorctl start syncthing) or others.
