#!/bin/bash

# Install syncthing.
punkt system syncthing

# Enable syncthing.
if punkt test --os "macOS"; then
    brew services start syncthing
else
    systemctl --user enable syncthing.service
    systemctl --user start syncthing.service
fi
