# This is a special alacritty config for launching
# terminal games (scripts/launchtermgames), in particular
# for Dungeon Crawl Stone Soup.

# Startup.

[terminal.shell]
program = "launchtermgames"

[env]
TERM = "xterm-256color"

# Font settings.

[font]
size = 26

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

# UI settings.

[mouse]
hide_when_typing = true

[window]
decorations = "None"
startup_mode = "Fullscreen"

# Custom colour scheme.

# Based on the default tiles colour theme,
# (which in turn is partially based on the
#  gnome terminal theme I think).
# Uses AA and AAA WCAG compliant colours
# (https://webaim.org/resources/contrastchecker/)
# dark and light, respectively, improving
# readability slightly. Some light colours
# are adapted to be more distinct from the
# brighter dark colours.
# Also uses a purple-tinted dark grey and
# more sandy off-white for white, which helps
# distinquish lighted from non-lighted areas.

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text   = "#000000"
cursor = "#ffffff"

[colors.normal]
black   = "#000000"  # Black
red     = "#dc3232"  # Medium-dark crimson
green   = "#4e9a06"  # Forest green
yellow  = "#926f36"  # Warm amber-brown
blue    = "#615dff"  # Vivid blue-violet
magenta = "#d333d1"  # Deep pink-purple
cyan    = "#06989a"  # Deep teal
white   = "#bbb2a1"  # Sandy off-white

[colors.bright]
black   = "#605666"  # Muted purple-grey
red     = "#f76c3e"  # Vivid burnt orange
green   = "#8ae234"  # Yellow-green / lime
yellow  = "#fce94f"  # Saturated yellow
blue    = "#6bacf5"  # Clear sky blue
magenta = "#fd71fa"  # Soft neon pink
cyan    = "#34e2e2"  # Bright aqua
white   = "#eeeeec"  # Near-white

# Xressources version, e.g., to import in terminal.sexy
#
# ! Background / Foreground
# *.background: #000000
# *.foreground: #ffffff
# 
# ! Cursor
# *.cursorColor: #ffffff
# 
# ! Normal (ANSI 0–7)
# *.color0:  #000000
# *.color1:  #dc3232
# *.color2:  #4e9a06
# *.color3:  #926f36
# *.color4:  #615dff
# *.color5:  #d333d1
# *.color6:  #06989a
# *.color7:  #bbb2a1
# 
# ! Bright (ANSI 8–15)
# *.color8:  #605666
# *.color9:  #f76c3e
# *.color10: #8ae234
# *.color11: #fce94f
# *.color12: #6bacf5
# *.color13: #fd71fa
# *.color14: #34e2e2
# *.color15: #eeeeec

