#!/bin/bash

### Utility ###

Inform()
{
    echo -e -n "\n\e[32m(-DOTF-)\e[39m $1 ...\n"
}

# Change pwd.
SetEnv()
{
    # Go to dotfiles dir.
    cd "$HOME/dotfiles"
}

# See SetOS.
SetPack()
{
    # Detect distribution.
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        DOTF_DISTR_U=$NAME
    elif type lsb_release >/dev/null 2>&1; then
        DOTF_DISTR_U=$(lsb_release -si)
    elif [ -f /etc/lsb-release ]; then
        . /etc/lsb-release
        DOTF_DISTR_U=$DISTRIB_ID
    else
        DOTF_DISTR_U=$(uname -s)
    fi

    DOTF_DISTR="${DOTF_DISTR_U,,}"

    # Determine the package manager.

    if command -v apt &> /dev/null ; then
        DOTF_PACK="apt" 
        DOTF_PACK_CMD="sudo apt install -y"
    elif command -v dnf &> /dev/null ; then
        DOTF_PACK="dnf" 
        DOTF_PACK_CMD="sudo dnf install -y"
    elif command -v pacman &> /dev/null ; then
        DOTF_PACK="pacman" 
        DOTF_PACK_CMD="sudo pacman -S"
    else
        DOTF_PACK="common"
        DOTF_PACK_CMD="echo Please install manually: "
    fi
}

# Set four variables:
# DOTF_OS       - linux or macos.
# DOTF_PACK     - the package manager, apt, dnf, or pacman, defaults to unknown.
# DOTF_PACK_CMD - command for installing packages using DOTF_PACK, defaults to echo.
SetOs()
{
    # Detect the operating system.
    UNAME=$(uname -s)
    if [ "$UNAME" = "Darwin" ]; then
        DOTF_OS="macos"
        DOTF_PACK="brew"
        DOTF_PACK_CMD="brew install"
    else
        DOTF_OS="linux"
        SetPack
    fi
}

### Modes (Minor) ###

DotBoot()
{
    SetOs
    if [ ! -d ~/dotfiles ]; then
        cd ~
        Inform "running bootstrap"
        # Ensure git is installed. 
        # Should be available on macOS.
        # Might be available on Linux, make sure:
        if [ "$DOTF_OS" = "linux" ]; then
            $DOTF_PACK_CMD git
        fi
        git clone https://github.com/pseifer/dotfiles.git ~/dotfiles
        SetEnv
        chmod +x dotf
    fi
}

DotInstall()
{
    SetEnv
    Inform "installing dotfiles"
    ./src/init
}

DotLink()
{
    SetEnv
    Inform "linking dotfiles"
    ts=$(/bin/date "+%Y-%m-%d_%H-%M-%S")
    backup="backup_$ts"
    mkdir -p "$backup"
    ./src/linkage "dotfiles.config" "$backup" "config.config"
}

DotUpdate()
{
    SetEnv
    Inform "updating dotfiles"
    git pull
}

DotPush()
{
    DotUpdate
    Inform "syncing dotfiles"
    git add src/*
    git add dotfiles/*
    git add dotf
    git add default/*
    git add README.md
    git commit
    git push
}

SystemUpdate()
{
    SetEnv
    SetOs
    Inform "updating system"
    ./src/"$DOTF_OS"/"$DOTF_PACK"/update 
}

SystemSetup()
{
    SetEnv
    SetOs
    Inform "setting up system (interactive)"
    ./src/setup "$DOTF_OS" "$DOTF_PACK" "$DOTF_PACK_CMD"
}

SystemSetupFull()
{
    SetEnv
    SetOs
    Inform "setting up system (auto)"
    ./src/setup "$DOTF_OS" "$DOTF_PACK" "$DOTF_PACK_CMD" "y"
}

CleanBackups()
{
    if [ -d ~/dotfiles ]; then
        SetEnv
        Inform "cleaning backups"
        rm -r backup_*/
    fi
}

CleanAll()
{
    CleanBackups
    if [ -d ~/dotfiles ]; then
        SetEnv
        Inform "cleaning local configuration"
        rm dotfiles.config
        rm config.config
    fi
}

### Modes (Major) ###

# Display documentation.
Help()
{
   echo -e "usage: \e[32mdotf\e[39m <command>"
   echo
   echo "These are the most common commands:"
   echo
   echo -e "    \e[32mdot install\e[39m        Setup a new system."
   echo -e "    \e[32mdot update\e[39m         Update dotfiles."
   echo
   echo "The following are more specific commands;"
   echo "usually, these do not need to be executed manually."
   echo
   echo "    dot-boot           Bootstrap the dotfile manager."
   echo "    dot-install        Install only the dotfile manager."
   echo "    dot-link           Link dotfiles on system."
   echo "    dot-update         Pull remote updates to dotfiles."
   echo "    dot-push           Push local changes to remote."
   echo "    system-setup       Install packages on a new system."
   echo "    system-update      Update the system."
   echo "    clean-backups      Remove dotfile backups."
   echo "    clean-all          Remove local config overwrites."
   echo
}

# Update the system.
Update()
{
    SystemUpdate 
    DotUpdate
    DotLink
}

# Install the system.
Install()
{
    DotBoot
    SystemSetup
    DotInstall
    DotLink
}

### Main Program ###

case "$1" in
    # Major modes.
    ("help")
        Help
        exit;;
    ("install")
        Install
        exit;;
    ("update")
        Update
        exit;;
    # Minor modes.
    ("dot-boot")
        DotBoot
        exit;;
    ("dot-install")
        DotInstall
        exit;;
    ("dot-link")
        DotLink
        exit;;
    ("dot-update")
        DotUpdate
        exit;;
    ("dot-push")
        DotPush
        exit;;
    ("system-setup")
        SystemSetup
        exit;;
    ("system-setup-full")
        SystemSetupFull
        exit;;
    ("system-update")
        SystemUpdate
        exit;;
    ("clean-backups")
        CleanBackups
        exit;;
    ("clean-all")
        CleanAll
        exit;;
    (*) 
        Help
        exit;;
esac
