#!/bin/bash

# Find out the current directory.
dotfiles_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Install punkt by setting link in ~/bin.
mkdir -p "${HOME}/bin/"
ln -sf "$dotfiles_dir/_punkt/punkt" "${HOME}/bin/punkt"

# Create .punktrc and tell punkt to use >this< directory.
cat > "${HOME}/.punktrc" << END
punkt_dotfiles="${dotfiles_dir}"
END

# Generate SSH keys, and update remote.
if [[ ! -f "${HOME}/.ssh/id_rsa.pub" ]]; then
    ssh-keygen -t rsa -b 4096 -C 'github@seifer.me'
    cat "${HOME}/.ssh/id_rsa.pub"
    git remote set-url origin 'git@github.com:pseifer/dotfiles.git'
fi

