#!/bin/bash

# (Re-)Install punkt.
# TODO

if [ -d "${HOME}/.dotfiles" ]; then
    echo "${HOME}/.dotfiles exists. Delete to reinstall."
    exit 0
fi

# Clone the repository, bare, to $HOME/.dotfiles
git clone --bare "https://github.com/pseifer/dotfiles" "${HOME}/.dotfiles"

# Temporary function for referring to the repo.
function _dotfiles {
    git --git-dir="${HOME}/.dotfiles/" --work-tree="${HOME}" "${@}"
}

# Checkout the repo. Creates backups of conflicting dotfiles.
if _dotfiles checkout; then
    echo "Checked out dotfiles."
else
    echo "Creating backup of conflicting dotfiles."
    mkdir -p .config-backup
    _dotfiles checkout 2>&1 | grep -E "\s+\." | awk "{print $1}" | xargs -I{} mv {} .config-backup/{}
fi
_dotfiles checkout

# Disable tracking of all $HOME (not really required with .gitignore).
# _dotfiles config status.showUntrackedFiles no

# Generate SSH keys, and update remote.
if [[ ! -f "${HOME}/.ssh/id_rsa.pub" ]]; then
    ssh-keygen -t rsa -b 4096 -C 'github@seifer.me'
    cat "${HOME}/.ssh/id_rsa.pub"
fi
_dotfiles remote set-url origin 'git@github.com:pseifer/dotfiles.git'

# Remove README.md from local.
_dotfiles update-index --assume-unchanged "${HOME}"/README.md
rm "${HOME}"/README.md
# Note: '_dotfiles update-index --no-assume-unchanged README.md' to track again.
