#!/bin/bash
# Clean and Update the System.
# Cleans first (in case of space issues) and again after updates.

cd "$HOME/dotfiles/src/linux/apt"

# Removes old revisions of snaps.
SnapClean()
{
    if command -v snap &> /dev/null ; then
	    set -eu
		sudo snap list --all | awk '/disabled/{print $1, $3}' |
			while read snapname revision; do
				sudo snap remove "$snapname" --revision="$revision"
	        done
    fi
}

# Cleanup old SNAP versions.
SnapClean

# Autoremove old packages and clean the cache.
sudo apt autoremove
sudo apt clean

# Vacuum journal logs.
sudo journalctl --vacuum-time=2d

# Clean the thumbnail cache.
rm -rf ~/.cache/thumbnails/*

# Finally, run a system update.
sudo apt update -y
sudo apt upgrade -y

# And autoremove/clean again.
sudo apt autoremove
sudo apt clean

# Update SNAP
if command -v snap &> /dev/null ; then
    sudo snap refresh
fi

# And also clean snap again.
SnapClean
