#!/bin/bash

# Install shellcheck linter.
punkt_pack_install shellcheck

# Install bashate
punkt_pack_install python3-bashate

# Install zoxide.
punkt_curl_bash "https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh"
# brew install zoxide

# On WSL, add links to Org and Projects on Windows Host.
grep -q icrosoft /proc/version && ln -s /mnt/d/Cloud/Org ~/Org && ln -s /mnt/d/Projects ~/Projects && ln -s /mnt/d/Proton/My\ Files/zsh_history ~/.zsh_history
