#!/bin/bash

# Install shellcheck linter.
punkt system shellcheck

# Install bashate.
punkt system python3-bashate

# Install zoxide.
if punkt test --os "maxOS"; then
    punkt system "zoxide"
else
    punkt curl --bash "https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh"
fi
