- name: Install essential build tools
  include_tasks: lib/packages.yml
  vars:
    packages:
      - libc-dev
      - gcc
      - g++
      - cmake
      - make
      - python3
      - python3-pip
      - python3-venv
      - cargo
