- name: Install tools for the terminal 
  include_tasks: lib/packages.yml
  vars:
    packages:
      - tmux        # terminal multiplexer
      - w3m         # terminal browser
      - tldr        # short command overview
      - ripgrep     # fast grep
      - tree        # print directory tree
      - rlwrap      # wrap readline
      - btop        # better top
      - fzf         # fast fuzzy finder
      - bat         # better cat with syntax highlighting
      - zoxide      # better cd with smarts
      - imagemagick # convert images
      - plocate     # find things with index
      - jc          # JSON-ify output from tools

- name: Install tools for the terminal (Debian)
  include_tasks: lib/packages.yml
  vars:
    packages:
      - fd-find     # find things
  when: ansible_os_family == "Debian"

- name: Install tools for the terminal (Generic)
  include_tasks: lib/packages.yml
  vars:
    packages:
      - fd          # find things
  when: ansible_os_family != "Debian"

# - name: Install zoxide
#   include_tasks: lib/download-run.yml
#   vars:
#     url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
#     cmd: zoxide
