- name: Install tools for the terminal 
  include_tasks: lib/packages.yml
  vars:
    packages:
      - tmux
      - w3m
      - tldr
      - ripgrep
      - tree
      - rlwrap
      - btop
      - fzf
      - bat
      - zoxide
      - imagemagick
      - plocate

- name: Install tools for the terminal (Debian)
  include_tasks: lib/packages.yml
  vars:
    packages:
      - fd-find
  when: ansible_os_family == "Debian"

- name: Install tools for the terminal (Generic)
  include_tasks: lib/packages.yml
  vars:
    packages:
      - fd
  when: ansible_os_family != "Debian"

# - name: Install zoxide
#   include_tasks: lib/download-run.yml
#   vars:
#     url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
#     cmd: zoxide
