#!/bin/bash

if punkt test --os "linux"; then
    # Download NeoVim and link.
    #curl -L "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz" | tar -C "$(punkt get-storage)/nvim-linux64" -xzf nvim-linux64.tar.gz
    punkt curl --tar "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
    #punkt link "nvim-linux64/bin/nvim" "nvim"
else
    # Install package.
    punkt system "nvim"
fi

