#!/bin/bash

if punkt test --os "linux"; then
    # Download NeoVim and link.
    punkt curl --tar "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
    punkt link "nvim-linux64/bin/nvim" "nvim"
    punkt system "python3-pip" "python3-venv"
else
    # Install package.
    punkt system "nvim"
fi
