#!/bin/bash

punkt_curl_gzip "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" "cs"
chmod +x "$PUNKT_STORAGE/cs"
"$PUNKT_STORAGE/cs" "setup"

# On Apple Silicon (M1, M2, ...):
# curl -fL https://github.com/VirtusLab/coursier-m1/releases/latest/download/cs-aarch64-apple-darwin.gz | gzip -d > cs
