#!/bin/bash

if punkt test --pack "apt"; then
    # Add PPA and install.
    sudo add-apt-repository ppa:aslatter/ppa -y 
    sudo apt install alacritty
    sudo update-alternatives --config x-terminal-emulator
else
    # Hope for the best on other distros.
    punkt system "alacritty"
fi

