#!/bin/bash

# If on macOS, install homebrew.
if punkt_os_is 'darwin'; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Install basic packages, depending on system.
if punkt_os_is 'darwin'; then
    punkt_pack_install tmux tree
else
    # Install very basic packages.
    punkt_pack_install zip tar git curl fontconfig

    # Install other essential tools.
    punkt_pack_install build-essentials tmux w3m ripgrep tree rlwrap make htop
fi

# Install GUI tools
if punkt_os_is 'darwin'; then
    brew install --cask firefox
else
    punkt_pack_install vlc gimp flatpak
    # flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
    # flatpak install flathub org.kde.kasts
    # flatpak install flathub com.github.GradienceTeam.Gradience
    # flatpak install org.gtk.Gtk3theme.adw-gtk3 org.gtk.Gtk3theme.adw-gtk3-dark
    # sudo snap install adw-gtk3-theme

    # gnome shell: gnome-tweaks gnome-shell-extensions chrome-gnome-shell
    # snap: install steam
    #if punkt test pack=apt; then
    #    wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg
    #    cat signal-desktop-keyring.gpg | sudo tee /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null
    #    echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main' | sudo tee /etc/apt/sources.list.d/signal-xenial.list
    #    sudo apt update && sudo apt install signal-desktop
    #fi
fi

# Make some directories.
mkdir -p ~/.config
mkdir -p ~/bin
