#!/bin/bash

# Create some directories, just in case.
mkdir -p ~/.config
mkdir -p ~/bin

if punkt test --os "darwin"; then
    # If on macOS, install homebrew.
    punkt curl --bash "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"

    # Install GUI tools.
    brew install --cask firefox

    # Install basic packages.
    punkt system "tmux" "tree"
else
    # Install very basic packages.
    punkt system "zip" "tar" "git" "curl" "fontconfig"

    # Install other essential tools.
    punkt system "libc-dev" "cmake" "gcc" "g++" "tmux" "w3m" "ripgrep" "tree" "rlwrap" "make" "btop"

    # Install GUI tools.
    punkt system "vlc" "gimp" "inkscape"
fi

# gnome shell: gnome-tweaks gnome-shell-extensions chrome-gnome-shell
# if punkt test pack=apt; then
#    wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg
#    cat signal-desktop-keyring.gpg | sudo tee /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null
#    echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main' | sudo tee /etc/apt/sources.list.d/signal-xenial.list
#    sudo apt update && sudo apt install signal-desktop
#fi
