#!/bin/bash

# Install ZSH and requirements / related tools.
common=(
    "fzf"
    "bat"
    "zoxide"
    "imagemagick"
)

if punkt_pack_is "apt"; then
    punkt_pack_install "${common[@]}" fd-find fim zsh tmux
    sudo snap install glow
else
    punkt_pack_install "${common[@]}" "fd" "glow"
fi

# Install fast-syntax-highlighting for ZSH.
punkt_rm "fast-syntax-highlighting"
punkt_git "https://github.com/zdharma-continuum/fast-syntax-highlighting.git"

# Install additional zsh-completions for ZSH.
punkt_rm "zsh-completions"
punkt_git "https://github.com/zsh-users/zsh-completions.git"

# Install s1ck3r prompt.
punkt_git "https://github.com/pseifer/s1ck3r"

# curl https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh > .local/share/punkt/fzf-key-bindings.zsh
punkt_curl https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh "fzf-key-bindings.zsh"
