#!/bin/bash

# ------------------------------------------------------------------------------
# ---------- Setup the home directory ------------------------------------------
# ------------------------------------------------------------------------------

mkdir -p ~/.programs-from-git     # system:source-installs
mkdir -p ~/bin                    # system:scripts
mkdir -p ~/.local/share/fonts     # system:fonts

# ------------------------------------------------------------------------------
# ---------- Detect the distribution -------------------------------------------
# ------------------------------------------------------------------------------

PACK="$1"
LOS="$2"

onlyif () {
    if [ "$LOS" = "$1" ]; then
        true
    else
        false
    fi
}

# ------------------------------------------------------------------------------
# ---------- Install core packages via package manager -------------------------
# ------------------------------------------------------------------------------

$PACK zip tar git curl # Required for setup.

$PACK w3m rlwrap cmake tmux htop fish fd-find ripgrep tree ranger

onlyif "fedora" && $PACK dnf-plugins-core copr-cli util-linux-user

onlyif "ubuntu" && $PACK fontconfig 

onlyif "ubuntu" && $PACK python3 python3-pip default-jre default-jdk

onlyif "ubuntu" && sudo add-apt-repository ppa:aslatter/ppa -y && sudo apt install alacritty

# Install latest stable NeoVim.

cd ~

rm -r ~/.programs-from-git/nvim-linux64

curl -fLOs https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
tar -xzvf nvim-linux64.tar.gz
rm nvim-linux64.tar.gz
mv nvim-linux64 ~/.programs-from-git
ln -s ~/.programs-from-git/nvim-linux64/bin/nvim ~/bin/nvim 

# Install Nerd Fonts (Source Code Pro)

cd ~/.local/share/fonts 
rm -f SauceCodeProNerdFont*
rm -f readme.md
rm -f LICENSE.txt

curl -OL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/SourceCodePro.zip
unzip SourceCodePro.zip
rm SourceCodePro.zip
fc-cache -f -v

# Install Scala tools via coursier.
cd ~

curl -fL "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" | gzip -d > cs
chmod +x cs
./cs setup
rm cs

