#!/bin/bash

# ------------------------------------------------------------------------------
# ---------- Setup the home directory ------------------------------------------
# ------------------------------------------------------------------------------

mkdir -p ~/.programs-from-git &&\ # system:source-installs
mkdir -p ~/bin &&\                # system:scripts
mkdir -p ~/Teaching &&\           # cloud:teaching
mkdir -p ~/Slides &&\             # cloud:slides
mkdir -p ~/Papers &&\             # cloud:papers
mkdir -p ~/Notes &&\              # cloud:notes
mkdir -p ~/Projects &&\           # projects
mkdir -p ~/Wallpaper              # wallpapers

# ------------------------------------------------------------------------------
# ---------- Detect the distribution -------------------------------------------
# ------------------------------------------------------------------------------

if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
elif type lsb_release >/dev/null 2>&1; then
    OS=$(lsb_release -si)
elif [ -f /etc/lsb-release ]; then
    . /etc/lsb-release
    OS=$DISTRIB_ID
else
    OS=$(uname -s)
fi

PACK="echo"

LOS="${OS,,}"

if [ "$LOS" = "fedora" ]; then
  PACK="sudo dnf install -y"
elif [ "$LOS" = "manjaro" ]; then
  PACK="sudo pacman -S"
elif [ "$LOS" = "ubuntu" ]; then
  PACK="sudo apt install -y"
elif [ "$LOS" = "debian" ]; then
  PACK="sudo apt install -y"
fi

onlyif () {
    if [ "$PLATFORM" = "$1" ]; then
        true
    else
        false
    fi
}

# ------------------------------------------------------------------------------
# ---------- Install core packages via package manager -------------------------
# ------------------------------------------------------------------------------

if install "Essential Packages"; then
    $PACK firefox w3m git rlwrap curl cmake tmux subversion \
          xrandr arandr zathura thunar htop xclip xournal \
          kitty fish fd-find ripgrep

    onlyif "fedora" &&\
        $PACK dnf-plugins-core copr-cli util-linux-user

    onlyif "ubuntu" &&\
        $PACK python3 python3-pip vlc apt-file snapd default-jre default-jdk &&\
        sudo snap install nextcloud
fi

cd ~

# Install latest stable NeoVim.

curl -fL https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
tar xzvf nvim-linux64.tar.gz
rm nvim-linux64.tar.gz
mv nvim-linux64 ~/.programs-from-git
ln -s ~/.programs-from-git/nvim-linux64/bin/nvim ~/bin/nvim 

# Install Nerd Fonts (Source Code Pro)

mkdir -p ~/.local/share/fonts
cd ~/.local/share/fonts && curl -OL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/SourceCodePro.zip
fc-cache -f -v
cd ~

# Install Scala tools via coursier.

curl -fL "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" | gzip -d > cs
chmod +x cs
./cs setup
rm cs

# Install LaTeX tools.

$PACK texlive texlive-fonts-extra biber latex-bibtex-extra latexmk

