#!/bin/bash

# ------------------------------------------------------------------------------
# ---------- Setup the home directory ------------------------------------------
# ------------------------------------------------------------------------------

mkdir -p "$HOME/Teaching"
mkdir -p "$HOME/Slides"
mkdir -p "$HOME/Papers"
mkdir -p "$HOME/Notes"
mkdir -p "$HOME/Projects"
mkdir -p "$HOME/Org"

# ------------------------------------------------------------------------------
# ---------- Detect the distribution -------------------------------------------
# ------------------------------------------------------------------------------

PACK="$1"
LOS="$2"

onlyif () {
    if [ "$LOS" = "$1" ]; then
        true
    else
        false
    fi
}

# ------------------------------------------------------------------------------
# ---------- Install extended packages via package manager ---------------------
# ------------------------------------------------------------------------------

$PACK firefox vlc xrandr arandr zathura thunar xclip xournal

onlyif "ubuntu" &&\
    $PACK apt-file snapd &&\
    sudo snap install nextcloud 

# Install LaTeX tools.

$PACK texlive-latex-extra biber latexmk 
