#!/bin/bash

# ------------------------------------------------------------------------------
# ---------- Detect the distribution -------------------------------------------
# ------------------------------------------------------------------------------

# Realistically, currently only (recent) Ubuntu is supported.

PACK="$1"
LOS="$2"

onlyif () {
    if [ "$LOS" = "$1" ]; then
        true
    else
        false
    fi
}

# ------------------------------------------------------------------------------
# ---------- Install core packages via package manager -------------------------
# ------------------------------------------------------------------------------

$PACK zip tar git curl fontconfig # Required for setup.

$PACK fish xclip w3m rlwrap cmake tmux htop bat fd-find ripgrep plocate tree ranger # Core packages.

# Set shell to fish.
chsh -s /usr/bin/fish

$PACK python3 python3-pip openjdk-17-jre openjdk-17-jdk openjdk-17-source

# Install alacritty via PPA and update default terminal (Ubuntu).
onlyif "ubuntu" && bash "$HOME/dotfiles/src/linux/alacritty.install"

# Install latest stable NeoVim.

bash "$HOME/dotfiles/src/linux/neovim.install"

# Install Nerd Fonts (Source Code Pro)

bash "$HOME/dotfiles/src/linux/nerd-fonts.install"

# Install glow

bash "$HOME/dotfiles/src/linux/glow.install"

# Install Scala tools via coursier.

bash "$HOME/dotfiles/src/linux/coursier.install"

# Generate SSH key, and update remote.

ssh-keygen -t rsa -b 4096 -C "github@seifer.me"
cat ~/.ssh/id_rsa.pub
git remote set-url origin git@github.com:pseifer/dotfiles.git
