#!/usr/bin/env bash

# Universal cheap "build server".
# Runs 'make clean' on startup if -c is specified.
# and then 'make' on any changed files.

# Requirements: make, entr
# Supported languages: LaTeX, C, Zig

# Initialise option flag with a false value
OPT_CLEAN='false'

# Process all options supplied on the command line 
while getopts ':c' 'OPTKEY'; do
    case ${OPTKEY} in
        'c')
            OPT_CLEAN='true'
            ;;
        *)
            echo "usage: bserve [-c]"
            exit 1
            ;;
    esac
done

# If the '-c' option is set, clean first.
if ${OPT_CLEAN}; then
    make clean
fi

# Observe various filetypes, and re-run make on changes.
# Note, that this is mainly useful for LaTeX and very small
# zig/c projects with low build times.
find . -name "*.zig" \
    -or -name "*.tex" \
    -or -name "*.bib" \
    -or -name "*.cls" \
    -or -name "*.c" \
    -or -name "*.h" |
    entr make
