#!/usr/bin/env lua

-- Lookup the search provider from the environment.
local provider = os.getenv("SEARCH_PROVIDER") or "https://duckduckgo.com/?q="

-- Build the query string from the provider, concatenated command line,
-- while replacing a leading ":" with "!", as a bang pattern.
local query = provider .. table.concat(arg, " "):gsub("^:", "!")

-- Open new tab in standard browser.
os.execute(('open "%s"'):format(query))
