#!/usr/bin/env python3

"""Demo for pscript.cli()."""

import pscript


def main(myj=None):
    """Demo for pscript.cli()."""
    if myj:
        m = myj
    else:
        m = {}
    print(m.get("name"))


if __name__ == "__main__":
    pscript.cli(globals(), load_files=True)
