#!/usr/bin/env bash

# Launcher for terminal games. 
# This is the startup program for Wezterm.
# Launch with 'wez'.

echo ""
echo "What do you want to play today?"
echo "  [1] DCSS"
echo "  [2] DCSS (underhound.eu)"
echo "  [0] quit"
echo ""

while true; do
  read -rn 1 -p "=> " answer
  case "$answer" in
    1)
      dcss
      break
      ;;
    2)
      sshpass -p terminal ssh -p 23 terminal@underhound.eu
      break
      ;;
    0)
      exit 0
      ;;
    *)
      echo ""
      ;;
  esac
done

