#!/usr/bin/env bash

# Launcher for terminal games, which is
# the startup program for launching alacritty
# with the .crawlacritty config (alias 'games').

GREEN='\033[0;32m'
YELLOW='\033[0;35m'
RESET='\033[0m'

print_with_key() {
  echo -e "  [${GREEN}$1${RESET}] $2"
}

print_menu() {
  clear
  echo ""
  echo "What do you want to play?"
  echo ""
  print_with_key 1 "Dungeon Crawl Stone Soup"
  print_with_key 2 "DCSS @ underhound.eu"
  print_with_key 3 "Nethack"
  echo ""
  print_with_key enter "terminal"
  print_with_key esc "quit"
  echo ""
  echo -en "${YELLOW}=>${RESET} "
}

# Guess screen resolution from rows and columns
# and decide whether to add padding.

read -r ROWS COLS < <(stty size)
RATIO=$(( COLS * 100 / ROWS ))
if [[ "$RATIO" -gt 460 ]]; then
  alacritty msg config 'window.padding.x=450'
else
  alacritty msg config 'window.padding.x=0'
fi

# Main: Read input and launch game/terminal/quit.

while true; do
  print_menu
  read -s -r -n 1 answer
  case "$answer" in
    1)
      dcss
      continue
      ;;
    2)
      sshpass -p terminal ssh -p 23 terminal@underhound.eu
      continue
      ;;
    3)
      nethack
      continue
      ;;
    "")
      clear
      zsh
      continue
      ;;
    $'\e')
      exit 0
      ;;
    *)
      continue
      ;;
  esac
done

