#!/bin/bash

# Display all kinds of files with syntax highlighting.
# Aliased to 'sml' in .aliases
fullfile="${1:-}"
filename=$(basename -- "$fullfile")
extension="${filename##*.}"

# Show markdown files with glow,
if [ "${extension}" = "md" ]; then
    glow --style "${HOME}/.config/glow/zenbones.json" "${1}"
# html files with W3M,
elif [ "${extension}" = "html" ]; then
    w3m "${1}"
# PDF with 'open',
elif [ "${extension}" = "pdf" ]; then
    open "${1}"
# directories with tree,
elif [ -d "${1}" ]; then
    tree -C "${1}"
# images with fim,
elif command -v identify >/dev/null &&
    command -v fim >/dev/null &&
    identify "${1}" 2>/dev/null 1>&2; then
    fim -o aa "${1}"
# everything else with batcat
elif command -v batcat >/dev/null; then
    batcat -pp --color=always "${1}"
elif command -v bat >/dev/null; then
    bat -pp --color=always "${1}"
# or cat, directly (if batcat is not installed).
else
    cat "${1}"
fi
