#!/usr/bin/env bash

# Launcher for terminal games, which is
# the startup program for launching alacritty
# with the .crawlacritty config (alias 'games').

# Settings

# Monitor 1 ("Desktop")
DESKTOP_C="DP-1"
DESKTOP_RES="3440x1440@99.982"
DESKTOP_FONT="26"
DESKTOP_PADDING="450"

# Monitor 2 ("TV") - 4k
TV_C="HDMI-1"
TV_RES="1920x1080@60.000"
TV_FONT="26"
TV_PADDING="0"

# Monitor 2 ("TV") - 4k
TV4K_C="HDMI-1"
TV4K_RES="3840x2160@60.000"
TV4K_FONT="53"
TV4K_PADDING="0"

# Utilities

GREEN='\033[0;32m'
RESET='\033[0m'

print_with_key() {
  echo -e "  [${GREEN}$1${RESET}] $2"
}

print_logo() {
  echo -e "\n\n  [[${GREEN}TuxBox${RESET}]]\n"
}

# The full TuxBox menu.
print_menu() {
  clear
  print_logo
  print_with_key c "Dungeon Crawl Stone Soup"
  print_with_key u "DCSS @ underhound.eu"
  print_with_key s "Steam"
  echo ""
  print_with_key y "YouTube"
  echo ""
  print_with_key t "switch to TV"
  print_with_key k "switch to TV (4k)"
  print_with_key d "switch to Desktop"
  echo ""
  print_with_key enter "Terminal"
  print_with_key esc "Quit"
  echo ""
  echo -n "  "
}

# Guess screen resolution from rows and columns
# and decide whether to add padding.

update_padding() {
    alacritty msg config 'window.padding.x=0'
    read -r ROWS COLS < <(stty size)
    RATIO=$(( COLS * 100 / ROWS ))
    if [[ "$RATIO" -gt 460 ]]; then
      alacritty msg config "window.padding.x=${DESKTOP_PADDING}"
    else
      alacritty msg config "window.padding.x=${TV_PADDING}"
    fi
}
update_padding

tux_term() {
    gnome-monitor-config set -LpM "${TV_C}" -t normal -m "${TV_RES}"
    alacritty msg config "window.padding.x=${TV_PADDING}"
    alacritty msg config "font.size=${TV_FONT}"
}

tux_4k() {
    gnome-monitor-config set -LpM "${TV4K_C}" -t normal -m "${TV4K_RES}"
    alacritty msg config "window.padding.x=${TV4K_PADDING}"
    alacritty msg config "font.size=${TV4K_FONT}"
}

no_tux_term() {
    gnome-monitor-config set -LpM "${DESKTOP_C}" -t normal -m "${DESKTOP_RES}"
    alacritty msg config "window.padding.x=${DESKTOP_PADDING}"
    alacritty msg config "font.size=${DESKTOP_FONT}"
}

launch_steam() {
    open "steam://open/bigpicture" &> /dev/null
}

# Open browser with special profile.
launch_browser() {
    firefox --profile ~/snap/firefox/common/.mozilla/firefox/51gg3zr6.tuxbox "$1" &> /dev/null
}

# Main: Read input and launch game/terminal/quit.

while true; do
  print_menu
  read -s -r -n 1 answer
  case "$answer" in
    c)
      dcss
      continue
      ;;
    u)
      sshpass -p terminal ssh -p 23 terminal@underhound.eu
      continue
      ;;
    n)
      nethack
      continue
      ;;
    t)
      tux_term
      continue
      ;;
    k)
      tux_4k
      continue
      ;;
    d)
      no_tux_term
      continue
      ;;
    s)
      launch_steam
      continue
      ;;
    y)
      launch_browser "https://youtube.com"
      continue
      ;;
    "")
      clear
      zsh
      continue
      ;;
    $'\e')
      exit 0
      ;;
    *)
      continue
      ;;
  esac
done

