# Colors Modus-Operandi
# https://github.com/protesilaos/modus-themes

[colors.primary]
background = '#ffffff'
foreground = '#000000'

[colors.normal]
black   = '#000000'
red     = '#a60000'
green   = '#006800'
yellow  = '#d7a400'
blue    = '#0031a9'
magenta = '#721045'
cyan    = '#005e8b'
white   = '#f2f2f2'

[colors.bright]
black   = '#595959'
red     = '#a0132f'
green   = '#00663f'
yellow  = '#ffc60a'
blue    = '#0000b0'
magenta = '#531ab6'
cyan    = '#005f5f'
white   = '#c4c4c4'
