
- block:
  - name: Configure openrazer
    include_tasks: lib/add-repo.yml
    vars:
      name: hardware_razer
      url: "http://download.opensuse.org/repositories/hardware:/razer/Debian_Unstable"
      key: "https://download.opensuse.org/repositories/hardware:razer/Debian_Unstable/Release.key"
      suite: "/"

  - name: Install openrazer
    include_tasks: lib/packages.yml
    vars:
      packages: openrazer-meta

- block:
  - name: Configure polychromatic
    include_tasks: lib/add-repo.yml
    vars:
      name: polychromatic
      url: "http://ppa.launchpad.net/polychromatic/stable/ubuntu"
      key: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xc0d54c34d00160459588000e96b9cd7c22e2c8c5"
      suite: focal
      component: main

  - name: Install polychromatic
    include_tasks: lib/packages.yml
    vars:
      packages: polychromatic
