
import = [
    # Load color theme.
    # "~/.config/alacritty/themes/modus-operandi.toml",
    "~/.config/alacritty/themes/zenbones-light.toml",
    # Load OS specific settings.
    "~/.config/alacritty/os.toml"
]

[window.padding]
x = 5
y = 5

[env]
TERM = "xterm-256color"

# Font settings.

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

# Keybindings

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
