# Load color theme.

import = [
    "~/.config/alacritty/themes/everforest_light.toml"
]

# Alacritty configuration, connecting to single tmux session 'base'.

[shell]
args = ["new-session", "-A", "-s", "base"]
program = "tmux"

# Window setup

[window]
decorations = "None"
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5

[env]
TERM = "xterm-256color"

# Font settings.

[font]
size = 12

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

# Keybindings

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

