# Alacritty configuration, connecting to single tmux session 'base'.

#[shell]
#args = ["new-session", "-A", "-s", "base"]
#program = "/opt/homebrew/bin/tmux"

# Window setup.

[window]
#decorations = "None"
startup_mode = "Maximized"

# Font size update.

[font]
size = 16

