#!/bin/bash

target="$HOME/.themes/xresources/gnome-shell"
filetarget="$target/gnome-shell.css"

mkdir -p "$target"

input="$HOME/.cache/wal/colors"
nl -v 0 ~/.cache/wal/colors | awk '{ print "@define-color color" $1, $2 ";"}' > "$filetarget"
cat gnome-shell.css >> "$filetarget"
